version: '3.4'
services:
  scrifeo:
    build: .
    links:
      - aws
    environment:
      - AWS_ENDPOINT=http://aws:4572
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - BUCKET=test-bucket
  aws:
    image: localstack/localstack
    environment:
      - SERVICES=s3
    expose:
      - 4572
    environment:
      - AWS_ENDPOINT=http://aws:4572
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - BUCKET=test-bucket
  aws-init:
    build: ./test/aws
    links:
      - aws
    environment:
      - AWS_ENDPOINT=http://aws:4572
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - BUCKET=test-bucket
