version: '3.4'
services:
  scrifeo:
    build: .
    links:
      - aws
    depends_on:
      - aws-init
  aws:
    image: localstack/localstack
    environment:
      - SERVICES=s3
    expose:
      - 4572
  aws-init:
    build: ./test/aws
    links:
      - aws
    depends_on:
      - aws
